### ISSUE TITLE
Sprint 1 - PBI 4 | HR dapat melihat rekapitulasi absen

### ISSUE THREAD

**Issue by AnastassyaG** [SI-RPL-2021/SIHURE-LARAVEL-SI4205#1]

**Comment by adlighozian** [comment]
button untuk lihat report belum tersedia 

![image](https://user-images.githubusercontent.com/71831676/115101298-00497d80-9f6d-11eb-98f8-13c4227e0ae4.png)

**Comment by AnastassyaG** [comment]
Tidak bisa push karena mengalami error  seperti berikut :
![image](https://user-images.githubusercontent.com/71958922/115836131-50c74c00-a441-11eb-95d6-4ba567ad27ca.png)
